artifact_uri: mlflow-storage\0\795af4fa370f48b8ae7a3b31f1779059\artifacts
end_time: 1555928858472
entry_point_name: ''
experiment_id: 0
lifecycle_stage: active
name: ''
run_uuid: 795af4fa370f48b8ae7a3b31f1779059
source_name: pipeline_example.py
source_type: 4
source_version: ''
start_time: 1555928858200
status: 3
tags: []
user_id: unknown
